
version: "3.2"

services:
  agr_file_generator:
    image: agrdocker/agr_file_generator:latest
    volumes:
      - type: volume
        source: agr_generated_files
        target: /usr/src/agr/tmp
        volume:
          nocopy: true
    environment:
      - NET=production
      - ALLIANCE_RELEASE=2.3.0
      - NEO4J_HOST=build.alliancegenome.org
      - FMS_API_URL=https://fmsdev.alliancegenome.org
      - API_KEY=${API_KEY}
      - DEBUG=True
    entrypoint:
      - python3
      - -u 
      - src/agr/app.py

volumes:
  agr_generated_files:
