
version: "3.2"

services:
  agr_file_generator:
    image: agrdocker/agr_file_generator:latest
    volumes:
      - type: volume
        source: agr_data_share
        target: /usr/src/app/tmp
        volume:
          nocopy: true
    environment:
      - PYTHONUNBUFFERED=1
      - NET=production
      - ALLIANCE_RELEASE=2.2.0
      - FMS_API_URL=https://fmsdev.alliancegenome.org
      - API_KEY=${API_KEY}
      - DEBUG=True
    entrypoint:
      - python3
      - -u 
      - src/agr/app.py

volumes:
  agr_data_share:
