# Settings used throughout the script.
threads: 1

# Default environmental variables.
# These Value SHOULD ONLY BE CHANGED VIA THE COMMAND LINE!!!
API_KEY: # Defaults to "None" if it cannot be found in the environment.
FMS_API_URL: https://fmsdev.alliancegenome.org
RELEASE_VERSION: 0.0.0
NEO4J_HOST: localhost
NEO4J_PORT: 7687
DEBUG: False
NEO_DEBUG: False
GENERATED_FILES_FOLDER: null
