# Settings used throughout the script.
threads: 1

# Default environmental variables.
API_KEY: # Defaults to "None" if it cannot be found in the environment.
FMS_API_URL: https://fms.alliancegenome.org
RELEASE_VERSION: 3.0.0
NEO4J_HOST: localhost
DEBUG: False
NEO_DEBUG: False
